apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'mkdir /var/log/k8s; touch /var/log/k8s/example1.log; i=0; while true; do echo "$i: $(date)" >> /var/log/k8s/example1.log; i=$((i+1)); sleep 1; done ']
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
  volumes:
  - name: log-volume
    hostPath:
      # Ensure the file directory is created.
      path: /var/log/k8s/
      type: DirectoryOrCreate
